// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1i-bDAGY-twL3UWY06HvQSF2l8ZtV3eI',
    appId: '1:680983638642:web:da363312299372f8c988eb',
    messagingSenderId: '680983638642',
    projectId: 'bookmytrainer-97573',
    authDomain: 'bookmytrainer-97573.firebaseapp.com',
    storageBucket: 'bookmytrainer-97573.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSlOYDiiwepBEc1AMgqBwILYqd40Ydp7M',
    appId: '1:680983638642:android:d7be2fd9c4061a30c988eb',
    messagingSenderId: '680983638642',
    projectId: 'bookmytrainer-97573',
    storageBucket: 'bookmytrainer-97573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZmMGDpb61fwom6Iz_ic3_F6L4hJ8Dqo',
    appId: '1:680983638642:ios:091a0b494c138ddfc988eb',
    messagingSenderId: '680983638642',
    projectId: 'bookmytrainer-97573',
    storageBucket: 'bookmytrainer-97573.firebasestorage.app',
    iosBundleId: 'com.example.bookmytrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZmMGDpb61fwom6Iz_ic3_F6L4hJ8Dqo',
    appId: '1:680983638642:ios:091a0b494c138ddfc988eb',
    messagingSenderId: '680983638642',
    projectId: 'bookmytrainer-97573',
    storageBucket: 'bookmytrainer-97573.firebasestorage.app',
    iosBundleId: 'com.example.bookmytrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1i-bDAGY-twL3UWY06HvQSF2l8ZtV3eI',
    appId: '1:680983638642:web:03a77a03910b18aac988eb',
    messagingSenderId: '680983638642',
    projectId: 'bookmytrainer-97573',
    authDomain: 'bookmytrainer-97573.firebaseapp.com',
    storageBucket: 'bookmytrainer-97573.firebasestorage.app',
  );
}
